version: '3.4'

services:
  configserver:
    image: "steeltoeoss/configserver"
    command: --spring.profiles.active=native --spring.cloud.config.server.native.searchLocations=/config
    volumes:
      - type: bind
        source: ./src/config
        target: /config
    ports:
      - "8888:8888"
  eurekaserver:
    image: "steeltoeoss/eurekaserver"
    ports:
      - "8761:8761"
  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      MSSQL_SA_PASSWORD: "SteeltoeR0cks"
      ACCEPT_EULA: "Y"
    depends_on:
      - configserver
      - eurekaserver
  musicservice:
    image: ${DOCKER_REGISTRY-}musicservice
    build:
      context: ./src/MusicStoreService
      dockerfile: Dockerfile
    depends_on:
      - configserver
      - eurekaserver
      - sqlserver
  shoppingcartservice:
    image: ${DOCKER_REGISTRY-}shoppingcartservice
    build:
      context: ./src/ShoppingCartService
      dockerfile: Dockerfile
    depends_on:
      - configserver
      - eurekaserver
      - sqlserver
  orderservice:
    image: ${DOCKER_REGISTRY-}orderservice
    build:
      context: ./src/OrderService
      dockerfile: Dockerfile
    depends_on:
      - configserver
      - eurekaserver
      - sqlserver
  musicstore:
    image: ${DOCKER_REGISTRY-}musicstore
    build:
      context: ./src/MusicStoreUI
      dockerfile: Dockerfile
    depends_on:
      - configserver
      - eurekaserver
      - musicservice
      - shoppingcartservice
      - orderservice
      - sqlserver
