eureka:
  client:
    shouldRegisterWithEureka: false
mysql:
  client:
    database: steeltoe2
    username: root
    password: steeltoe
DefaultAdminUsername: Administrator@test.com
DefaultAdminPassword: YouShouldChangeThisPassword1!