---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: mysql-connector
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: mysql-connector
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.flavours: steeltoe
    tanzu.app.live.view.application.name: mysql-connector
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  env:
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: true
  - name: DOTNET_NOLOGO
    value: true
  build:
    env:
    - name: DOTNET_CLI_TELEMETRY_OPTOUT
      value: true
    - name: DOTNET_NOLOGO
      value: true
  serviceClaims:
  - name: db
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ClassClaim
      name: my-mysql-service
  source:
    git:
      url: https://github.com/SteeltoeOSS/Samples.git
      ref:
        branch: main
